In [2]:
import pandas as pd 
import numpy as np
import os

In [3]:
df = pd.read_csv('last12months/12months/d_test_filled.csv')

/home/leonardo/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (22,24,26,28) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [8]:
first10 = df.head(10)
first10.to_excel('last12months/12months/first_10Row_204300479.xlsx')

In [5]:
df['Taratura sensore'].unique() 

array([ nan, -2.3])

In [6]:
df['Standby'].unique() 

array([nan,  0.])

In [7]:
df['Modo service'].unique() 

array([nan,  0.])